### ISSUE TITLE
Broken dependencies?

### ISSUE THREAD

**Issue by vvnekb** [TileDB-Inc/TileDB-Geospatial#20]
It seems that some dependencies are broken in this image, at least `gdal` and `rio` are not working correctly:
```
C:\Users\vvnx3>docker run -u 0 -it --rm tiledb/tiledb-geospatial /bin/bash
root@fe0b3d1fc360:/# rio --help
Traceback (most recent call last):
  File "/usr/local/bin/rio", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyparsing>=2.1.6' distribution was not found and is required by snuggs
root@fe0b3d1fc360:/# gdalinfo --formats
gdalinfo: error while loading shared libraries: libproj.so.17: cannot open shared object file: No such file or directory
```

**Comment by normanb** [comment]
@vvnekb I can confirm, looks like the latest update to the more recent versions of GDAL broke things. I will do some testing and resolve the issues.
